@echo off
setlocal

set DIST_ROOT_NAME=dist_incl
set DIST_ROOT_PATH=%~dp0dist_incl
set REMOVE_FOLDER_CMD=rmdir /s /q

%REMOVE_FOLDER_CMD% %DIST_ROOT_PATH%\tk\demos
%REMOVE_FOLDER_CMD% %DIST_ROOT_PATH%\tk\images
%REMOVE_FOLDER_CMD% %DIST_ROOT_PATH%\tk\msgs
%REMOVE_FOLDER_CMD% %DIST_ROOT_PATH%\tcl\encoding
%REMOVE_FOLDER_CMD% %DIST_ROOT_PATH%\tcl\http1.0
%REMOVE_FOLDER_CMD% %DIST_ROOT_PATH%\tcl\msgs
%REMOVE_FOLDER_CMD% %DIST_ROOT_PATH%\tcl\opt0.4
%REMOVE_FOLDER_CMD% %DIST_ROOT_PATH%\tcl\tzdata
